// This file is automatically generated. Do not edit it directly.
import { env } from "@/env";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  env.VITE_SUPABASE_URL,
  env.VITE_SUPABASE_PUBLISHABLE_KEY
);
